name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # or any other version supported by your project

      - name: Install Render CLI
        run: npm install -g render-cli

      - name: Authenticate Render CLI
        run: render login --api-key ${{ secrets.RENDER_API_KEY }}

      - name: Deploy to Render
        run: render deploy --service-id ${{ secrets.RENDER_SERVICE_ID }} --branch main

