# Your workflow name.
name: Deploy to Render

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      # Install Render CLI
      - name: Install Render CLI
        run: curl -fsSL https://render.com/install | bash

      # Authenticate Render CLI
      - name: Authenticate Render CLI
        run: render login --api-key ${{ secrets.RENDER_API_KEY }}

      # Deploy to Render
      - name: Deploy to Render
        run: render deploy --service-id ${{ secrets.RENDER_SERVICE_ID }} --branch main
